server.port: 8080
server.forward-headers-strategy: native

logging:
  config: classpath:config/logback-dev.xml
  level:
    root: WARN
    org.springframework.web.reactive.function.client: trace
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

spring:
  application:
    name: challengers
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DB명?serverTimezone=UTC
    username: 계정
    password: 비밀번호
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      format_sql: true
      show-sql: true
      use_sql_comments: true
  codec:
    max-in-memory-size: 30MB # 게시글 사진 용량

challengers:
  path:
    prefix: ./challengers # TODO 나중에 올릴때 수정 필요
    logs: /logs
    files: /files
  properties:
    static:
      path: classpath:/config/challengers-dev.properties

server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지
    whitelabel.enabled: true