server.port: 8080

logging:
  config: classpath:config/logback-dev.xml
  level:
    root: WARN
    org.springframework.web.reactive.function.client: trace

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

spring:
  application:
    name: challengers
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/challengers?serverTimezone=UTC
    username: root
    password: 2588
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true


challengers:
  path:
    prefix: ./challengers # TODO 나중에 올릴때 수정 필요
    logs: /logs
    files: /files
  properties:
    static:
      path: classpath:/config/challengers-dev.properties

server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지
    whitelabel.enabled: true